// TA observation prompts derived from the assignment descriptions. These do not add rubric criteria.
globalThis.GUIDANCE = {
 A1: [
  ['Show A/D moving left/right and W/S forward/back without turning the object.', 'In Mover.cs, inspect Keyboard.current input and a combined world-space X/Z direction. Movement must be custom scripted. Tank controls do not satisfy this item.'],
  ['Watch for consistent movement speed; ask where frame-rate independence happens.', 'Find Time.deltaTime applied to displacement. Trace the actual movement path; merely mentioning deltaTime in unused code is not evidence.'],
  ['Show movement settings on the selected player in the Inspector.', 'Check that serialized fields (public or [SerializeField]) feed the movement calculation rather than unused fields beside hardcoded speeds.'],
  ['Compare diagonal movement with a single axis over a similar interval.', 'Check normalization or clamping of the combined direction before speed is applied. Independently adding full X and Z speeds causes a diagonal boost.'],
  ['Show the Player prefab asset and the player in the scene.', 'Inspect Assets/Prefabs/Player.prefab and its movement component. A renamed scene object alone is not a prefab.'],
  ['Hold Left Shift while moving, then release it; speed should increase and return.', 'Trace the Shift condition to a separate Inspector-exposed running speed. Confirm the running speed is actually used.'],
  ['Move the player and show the Main Camera beneath Player in the Hierarchy.', 'Check the camera’s parent and local offset. A camera that follows through a separate script does not meet the stated parenting criterion.']
 ],
 A2: [
  ['Watch several spawn intervals; instances should appear rhythmically, not every frame.', 'In Spawner.cs, find the Time.deltaTime accumulator, interval comparison and timer reset/subtraction. Instantiate must be conditional.'],
  ['Toggle the spawner off, wait, then on during Play Mode. Spawning pauses and resumes.', 'Trace the input or trigger to the active flag. Inactive state should pause instantiation and timer accumulation. An Inspector-only toggle is not the requested in-game control.'],
  ['Expand the active list in the Inspector and wait until capacity is reached.', 'Confirm spawned instances enter List<GameObject> and a capacity check prevents extra spawns. A spawn counter without an active list is insufficient.'],
  ['Move the player into a spawned object and show the contact being detected.', 'Inspect OnTriggerEnter or OnCollisionEnter, player filtering, colliders and Rigidbody setup. For the template trigger setup, the collectible has a trigger collider and kinematic Rigidbody.'],
  ['Show score or another state value change after contact. Inspector or Console evidence is sufficient.', 'Follow the contact callback into the state update. No HUD is required; do not deduct for the absence of one.'],
  ['Collect an object and show it disappear from the scene/Hierarchy.', 'Find Destroy(gameObject) or equivalent despawning in the collection path. Hiding a mesh while leaving an active collectible is not cleanup.'],
  ['During Play Mode, drag an instance outside the arena in Scene view, or show it expire via a lifetime timer.', 'Accept a boundary trigger, position check, or lifetime timer. The current Notion checklist explicitly accepts timed destruction; objects need not move away by themselves.'],
  ['After collection and boundary/lifetime cleanup, show the list count drop and spawning resume without errors.', 'Inspect removal of destroyed references on each destruction path. Check that list mutation is safe and stale entries do not permanently consume capacity.']
 ],
 A3: [
  ['Show the .inputactions asset, Move action and composite bindings, then demonstrate movement.', 'Inspect the Action Map and 2D Vector composites (WASD and arrow keys in the brief), enabled actions and InputActionReference reading. Direct Keyboard.current polling or Input.GetAxis does not satisfy this item.'],
  ['Look left/right and up/down in first person. Pitch stops before the view flips.', 'Check the child camera, body yaw, pitch clamped to −90…90, a Look action bound to <Mouse>/delta and Inspector-exposed sensitivity.'],
  ['Show responsive movement, falling/landing, stairs and slopes in the test scene.', 'Trace CharacterController.Move, Time.deltaTime, gravity accumulation, isGrounded and exposed movement speed. Inspect controller step/slope settings as supporting evidence.'],
  ['Jump from the ground and try pressing Jump again in mid-air; no extra air jump should occur.', 'Read Jump from the same actions asset. Check isGrounded, exposed jumpHeight, initial upward velocity and ongoing gravity.'],
  ['Touch a collectible; it disappears and score or another game state changes.', 'Check OnTriggerEnter player filtering, destruction and state registration. An Inspector value or Debug.Log is acceptable state evidence.'],
  ['Aim at the power-up and press Interact. Show the speed boost start and expire.', 'Trace a camera raycast within range and Interact from the same actions asset. Check Coroutine/expiry timing and restoration of baseline speed. Touch-only activation does not satisfy this item.'],
  ['Touch a hazard and show damage, knockback or respawn.', 'Inspect contact detection and the actual penalty/state change. A hazard that only looks dangerous does not establish an impact.']
 ],
 A4: [
  ['Click walkable ground and show navigation, the destination marker and confirmation sound.', 'In ClickToMove.cs, inspect the camera raycast, Walkable layer mask, NavMeshAgent destination, marker and sound. All are part of this combined item.'],
  ['Let the pursuer approach and stay in contact. Health drops at controlled intervals rather than draining each frame.', 'In Chaser.cs, inspect refreshed destinations, contact handling and damage cooldown (or an equivalent rate limit). Check that sustained contact is handled.'],
  ['Collect an item and take a hit; score and health update. Resize the Game view or switch aspect ratios.', 'Check opposite-edge RectTransform anchors and CanvasScaler Scale With Screen Size (brief: 1280×720). Event-driven updates are preferred, but per-frame updates also pass this checklist.'],
  ['Demonstrate pickup, hit and power-up: each has sound and particles. Show speed rise temporarily and return.', 'Trace all three contact paths and audio/FX calls. Confirm the power-up changes agent speed for a limited time and restores it. Inspect particle lifetime and cleanup as diagnostic guidance.'],
  ['Listen for the purpose of five choices: move click, HUD, pickup, hit and power-up feedback.', 'Match each explanation to its implementation. “It plays a sound” is not a UX rationale; identify what it tells the player or which confusion it removes.'],
  ['Click a wall or unreachable platform. The response differs clearly from a confirmed move.', 'Inspect reachability/path handling and the refusal response. A raycast that misses the entire level may simply be ignored. SetDestination acceptance alone need not prove a complete reachable path.'],
  ['Hear a partially 3D source and a 2D source; listen as the pursuer approaches and hear why each was chosen.', 'Check Spatial Blend and listener position. The elevated camera can make floor-level 3D sounds too quiet; inspect Min Distance/listener placement. At least one audible partially 3D source and one 2D source are required.']
 ],
 A5: [
  ['The dog card is moved and turned. Doggy stays on it, standing, follows without jumping and disappears when the card is covered. The student shows the script that does this.', 'Find a script the student wrote that calls tracker.TryGetPose for tag ID 1 and moves Doggy\u2019s object there. It will look similar to TreatAnchor.cs, which is the supplied example. Attaching TreatAnchor itself to Doggy does not meet the item. Doggy\u2019s size is not graded.'],
  ['The treat moves into range: the jaw opens gradually and a sound plays. The treat moves away: the jaw closes. The distance value is shown in the Inspector.', 'Check a distance comparison against an Inspector value, and a jaw rotation that is blended over several frames (Lerp, Slerp or RotateTowards). A jaw that snaps open in one frame fails. The sound is the student\u2019s own and plays once per opening, not on every frame.'],
  ['The treat stays in range. After the hold time the tail wags and a sound and a particle effect play. Doggy stays happy while the treat is close; the tail stops when it leaves. Repeating it shows that the timer starts from zero.', 'Check a timer that counts up while the treat is in range and is reset when it leaves, with the duration in the Inspector. The tail is switched with Animator.SetBool("TailWag", \u2026). Sound and particle effect are both required; if either is missing the item fails.'],
  ['While Doggy is happy the treat card is covered: the treat disappears with an effect and a sound, the jaw closes and the tail stops. The student says why tracking was lost. Uncovered, the treat appears with effect and sound, and Doggy is only happy after the timer has run again. The same is shown for the dog card.', 'Check that the interaction only uses positions while both cards are tracked. Effects for the treat card mean TreatAnchor.cs was changed or replaced. The effect has to sit on an object that stays active. The tracker reports a loss about a quarter of a second after the card is covered; that delay is normal.'],
  ['The treat moves around Doggy, also to where the head cannot follow, and the dog card is turned. The head follows the treat and stops at its limit.', 'Check that the direction to the treat is worked out in Doggy\u2019s local space (for example InverseTransformPoint), that the turn limit is an Inspector value, and that the head turns over several frames. This item counts only when items 1 to 4 all work.'],
  ['A second dog stands on the card with tag ID 2. Both dogs open the jaw and become happy. Something visible happens between the dogs, and the student says in one sentence how it works.', 'Check a second marker object on tag ID 2 and an interaction that runs for each dog. What the dogs do to each other can be simple, but it must be visible and the student\u2019s own choice; the examples on the assignment page are acceptable. This item counts only when item 5 works.']
 ],
 A6: [
  ['Two teleports to different spots: thumbstick forward aims at the floor or rug, release lands there. Then a snap turn left and a snap turn right.', 'Show the Teleportation Area on the floor or rug and the locomotion components on the XR Origin (teleport and snap turn). The view must turn in fixed steps; continuous turning does not meet the item.'],
  ['Both objects are picked up.', 'Select one object and show XRGrabInteractable with its own Attach Transform, placed at a sensible grip point such as a handle. If both objects are held by their pivot, the item fails. The objects may be the Part B task objects.'],
  ['The wrong object is held at a socket: no preview and no snap. Then the right objects are placed.', 'Show the Interaction Layer Mask on one task socket and on its object. Each socket/object pair needs its own layer (in tutorial 1.4 all hats share one). The task sockets are new ones, at least two, separate from the hat hooks.'],
  ['The display counts up as the objects are placed, starting at nothing placed, for example 0/2 → 1/2 → 2/2.', 'In PlacementGoal.cs (on one manager object, not on the sockets): AddListener on both selectEntered and selectExited, and a counting method that checks hasSelection on each socket and is also called at the start. The total comes from the socket list, not a typed number. A ++/-- counter does not meet the item. The text sits on a World Space canvas.'],
  ['With every socket filled, the object opens gradually (about a second or longer), and the sound or particles play once.', 'Show the state that says "complete", the code in Update() that moves towards it with Lerp or MoveTowards, and where the effect is started. The effect must start once at the moment of completion, not every frame. This logic must be in PlacementGoal.cs; a ready-made _Course Library script does not count.'],
  ['One object is taken out: the display drops by one and the response closes smoothly. Put back: it opens again and the effect plays again.', 'Show the code that switches the state back when an object is removed. The response returns from wherever it is (also mid-opening), not by snapping to closed. The effect must play again on the next completion, so a "played once ever" flag fails.']
 ]
};
